# Generated by Django 3.0.5 on 2020-04-14 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='customers',
            new_name='Customer',
        ),
    ]
